apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      tier: todo-backend
  template:
    metadata:
      labels:
        tier: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: mahendravarmasa/todobackend:daaccac2e5b432e69ed0d4817d5ab4ae62f9751a
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URL
              value: "mongodb://mongodb:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: NodePort
  selector:
    tier: todo-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30008