apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      tier: todo-frontend
  template:
    metadata:
      labels:
        tier: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: mahendravarmasa/todofrontend:2292f48292f116c48f408e02e4b09b37e73cf9a3
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://65.0.29.32:30008"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  type: NodePort
  selector:
    tier: todo-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007
